"""
F-OS Domain Instantiation Factory.

Given a substrate description (dimensions, physics, signals), produces:
  1. Domain embedder stubs with DomainMatrix specs
  2. Projection matrices (initial W_d)
  3. Invariant checks adapted to the domain
  4. SubstrateConfig for the 3×3 matrix
  5. OpenCode agent definitions (templates)

This is the mechanism that makes F-OS generic.
HAPOS = instantiate(health physics).
RetailOS = instantiate(retail physics).
EduOS = instantiate(education physics).

The physics differ. The architecture is identical.

Usage:
  config = SubstrateConfig(name="RetailOS", dimensions=[
      SubstrateDimension("D", "Demand", "How accurately can we predict demand?",
                         "ARIMA + external regressors", 0.30),
      SubstrateDimension("S", "Supply", "How efficiently is inventory flowing?",
                         "Little's Law: L = λW", 0.30),
      ...
  ])
  result = instantiate(config, domains={
      "demand_forecast": DomainSpec(variables=["trend","seasonality","external"], ...),
      "inventory_flow": DomainSpec(variables=["throughput","wip","cycle_time"], ...),
  })
"""
from __future__ import annotations
from dataclasses import dataclass, field
import numpy as np
from src.core.fos import SubstrateConfig, SubstrateDimension, DomainMatrix, ProjectionMatrix


@dataclass
class DomainSpec:
    """Specification for one domain in the new substrate."""
    name: str                           # "demand_forecast"
    variables: list[str]                # ["trend", "seasonality", "external"]
    units: list[str]                    # ["units/day", "index", "composite"]
    equations: list[str]                # ["ARIMA(p,d,q)", "Fourier decomp", "regression"]
    sub_scores_served: list[str]        # ["D", "S"]
    phi_output_names: dict[str, list[str]] = field(default_factory=dict)
    # {"D": ["phi_trend", "phi_seasonal"], "S": ["phi_supply_signal"]}


@dataclass
class InstantiationResult:
    """Everything generated by the instantiation factory."""
    config: SubstrateConfig
    domain_matrices: dict[str, DomainMatrix]      # Initial empty matrices per domain
    projections: dict[str, dict[str, ProjectionMatrix]]  # {domain: {sub_score: W_d}}
    embedder_stubs: dict[str, str]                # {domain: Python code stub}
    invariant_stubs: list[str]                     # Invariant descriptions
    agent_template: str                            # OpenCode agent definition template


def instantiate(config: SubstrateConfig, domains: dict[str, DomainSpec]) -> InstantiationResult:
    """
    The universal factory. Takes a substrate description, produces
    everything needed to run a self-improving F-OS instance.
    
    What's generated (inherits architecture):
      - DomainMatrix specs (k rows × n tiers per domain)
      - Projection matrices (identity default, optimized by Embedding Ratchet)
      - Embedder stubs (subclass DomainEmbedder, implement compute_matrix)
      - Invariant check stubs (adapted I1-I8 for the new domain)
      - Agent definition template (for OpenCode)
    
    What's inherited (unchanged):
      - The 3×3 matrix architecture
      - The ratchet protocol (modify → measure → keep/discard)
      - The loop mechanics (L1 execute, L2 learn, L3 meta-learn)
      - The coupling computation
      - The synthesis equation: F(t) = α·N(t) + β·I(t)
      - The invariant framework
    """
    result_matrices: dict[str, DomainMatrix] = {}
    result_projections: dict[str, dict[str, ProjectionMatrix]] = {}
    result_stubs: dict[str, str] = {}

    for domain_name, spec in domains.items():
        k = len(spec.variables)
        n = config.timescale_tiers

        # Empty domain matrix (populated when embedder runs)
        dm = DomainMatrix(
            domain=domain_name,
            sub_scores_served=spec.sub_scores_served,
            row_names=spec.variables,
            row_units=spec.units,
            row_equations=spec.equations,
            tier_labels=[f"T{i}" for i in range(n)],
            data=np.zeros((k, n)),
            confidence=np.ones((k, n)),
        )
        result_matrices[domain_name] = dm

        # Projection matrices: one per sub-score served
        projections: dict[str, ProjectionMatrix] = {}
        for sub_score in spec.sub_scores_served:
            output_names = spec.phi_output_names.get(sub_score, [f"phi_{domain_name}_{i}" for i in range(min(k, 3))])
            m = len(output_names)
            # Default: truncated identity (first m rows of k variables)
            W = np.zeros((m, k))
            for i in range(min(m, k)):
                W[i, i] = 1.0
            projections[sub_score] = ProjectionMatrix(
                domain=domain_name,
                target_sub_score=sub_score,
                matrix=W,
                output_names=output_names,
            )
        result_projections[domain_name] = projections

        # Embedder stub (Python code template)
        result_stubs[domain_name] = _generate_embedder_stub(domain_name, spec, config)

    # Invariant stubs (adapted from universal I1-I8)
    invariant_stubs = _generate_invariant_stubs(config)

    # Agent template
    agent_template = _generate_agent_template(config, domains)

    return InstantiationResult(
        config=config,
        domain_matrices=result_matrices,
        projections=result_projections,
        embedder_stubs=result_stubs,
        invariant_stubs=invariant_stubs,
        agent_template=agent_template,
    )


def _generate_embedder_stub(domain: str, spec: DomainSpec, config: SubstrateConfig) -> str:
    vars_str = ", ".join(spec.variables)
    subs_str = ", ".join(f'"{s}"' for s in spec.sub_scores_served)
    return f'''"""
{domain.title()} Domain Embedder — Auto-generated by F-OS instantiate.
Variables: {vars_str}
Serves: {", ".join(spec.sub_scores_served)}
"""
import numpy as np
from src.core.fos import DomainEmbedder, DomainMatrix

class {domain.title().replace("_","")}Embedder(DomainEmbedder):
    def __init__(self):
        super().__init__(domain="{domain}", sub_scores_served=[{subs_str}])
        # TODO: register projections per sub-score

    def compute_matrix(self, **kwargs) -> DomainMatrix:
        # TODO: implement governing equations for {vars_str}
        data = np.zeros(({len(spec.variables)}, {config.timescale_tiers}))
        return DomainMatrix(
            domain="{domain}",
            sub_scores_served=[{subs_str}],
            row_names={spec.variables},
            row_units={spec.units},
            row_equations={spec.equations},
            data=data,
        )
'''


def _generate_invariant_stubs(config: SubstrateConfig) -> list[str]:
    dims = ", ".join(d.id for d in config.dimensions)
    return [
        f"I1: Lossless Archive — replay events → state identical for {dims}",
        f"I2: Variability — aggregates have σ, CV for all {dims} components",
        f"I3: Coupling — all cross-dimension pairs computed",
        f"I4: Gradient — ∂F/∂Φ decomposes across {dims}",
        f"I5: Invertibility — past state reconstructable",
        f"I6: Semantic Bridge — context linked to quantitative state",
        f"I7: Monotonicity — F non-increasing per {dims} independently",
        f"I8: Calibration — precision within 1σ of empirical",
    ]


def _generate_agent_template(config: SubstrateConfig, domains: dict[str, DomainSpec]) -> str:
    domain_list = "\n".join(f"  - {d}: {', '.join(s.sub_scores_served)}" for d, s in domains.items())
    dim_list = "\n".join(f"  - {d.id}: {d.name} — {d.physics_question}" for d in config.dimensions)
    return f"""# {config.name} — F-OS Agent Configuration
# Auto-generated. Customize per domain.

## Substrate Dimensions
{dim_list}

## Domain Embedders
{domain_list}

## Universal Architecture (inherited)
- 3×3 Matrix: 3 substrates × 3 loops = 9 cells
- Three ratchets: params (L2), embeddings (Embedding Ratchet), composition (L3)
- Eight invariants (adapted for {config.name})
- Unified objective: F(t) = α·N(t) + β·I(t)
"""
